
tasks:
  - name: Install pre-request
    before: echo 'before the init'
    init: | 
          pip install -r requirements.txt  # runs during prebuild
          gp sync-done installation
    command: echo 'start script'
  
  - name: Install spacy model
    init: |
        gp sync-await installation
        python -m spacy download en_core_web_sm


vscode:
  extensions:
    - ms-azuretools.vscode-docker