# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install pre-request
    before: echo 'before the init'
    init: pip install -r requirements.txt  # runs during prebuild
    command: echo 'start script'

