image:
    file: Dockerfile
tasks:
  - name: Install pre-request
    init: | 
          pip3 install -r requirements.txt  # runs during prebuild
          gp sync-done installation

  - name: Install spacy model
    init: |
        gp sync-await installation
        python -m spacy download en_core_web_sm


vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - almenon.arepl
